"""Domain enumerations for the fault data module mapper.

All enums are ``str``-backed so they serialise cleanly to the JSON values
expected by the canonical S1000D fault data module schema.

Naming convention:
  - Python identifiers use UPPER_SNAKE_CASE
  - String values use the exact casing from the canonical schema
"""

from __future__ import annotations

from enum import Enum, unique


# ═══════════════════════════════════════════════════════════════════════
#  MAPPING PIPELINE ENUMS
# ═══════════════════════════════════════════════════════════════════════


@unique
class FaultMode(str, Enum):
    """Content mode — exactly one must be active per data module.

    Drives the ``allOf/if-then`` conditional in the canonical schema:
    when mode is FAULT_REPORTING only ``faultReporting`` is populated,
    when mode is FAULT_ISOLATION only ``faultIsolation`` is populated.
    """

    FAULT_REPORTING = "faultReporting"
    FAULT_ISOLATION = "faultIsolation"


@unique
class MappingStrategy(str, Enum):
    """How a particular target field value was produced.

    DIRECT — copied verbatim from a source field.
    RULE   — generated by deterministic business logic.
    LLM    — produced via LLM semantic interpretation (never trusted
             alone; the assembler always verifies and owns the final value).
    """

    DIRECT = "direct"
    RULE = "rule"
    LLM = "llm"


@unique
class ValidationStatus(str, Enum):
    """Automated lifecycle status of a canonical fault data module record.

    Values match the schema's ``validationStatus`` enum exactly.
    """

    PENDING = "pending"
    SCHEMA_FAILED = "schema_failed"
    COMPLETENESS_FAILED = "completeness_failed"
    BUSINESS_RULE_FAILED = "business_rule_failed"
    REVIEW_REQUIRED = "review_required"
    APPROVED = "approved"
    REJECTED = "rejected"
    STORED = "stored"


@unique
class ReviewStatus(str, Enum):
    """Human review status — separate from automated ``ValidationStatus``.

    Supports a staged-trust workflow where automated checks pass first,
    then a human reviewer signs off before the module reaches STORED.
    """

    NOT_REVIEWED = "not_reviewed"
    IN_REVIEW = "in_review"
    CHANGES_REQUESTED = "changes_requested"
    APPROVED = "approved"
    REJECTED = "rejected"


@unique
class ValidationOutcome(str, Enum):
    """Outcome for an individual automated validation check."""

    PASSED = "passed"
    FAILED = "failed"
    WARNING = "warning"
    NOT_RUN = "not_run"


@unique
class ValidationSeverity(str, Enum):
    """Severity level for an individual validation issue.

    ERROR   — structural or business-rule violation that prevents
              the module from being considered valid.
    WARNING — non-blocking issue; module can proceed but should be
              flagged for human review.
    INFO    — informational note; no action required.
    """

    ERROR = "error"
    WARNING = "warning"
    INFO = "info"


# ═══════════════════════════════════════════════════════════════════════
#  S1000D CONTENT ENUMS
# ═══════════════════════════════════════════════════════════════════════


@unique
class FaultEntryType(str, Enum):
    """Discriminator for fault-entry variants inside faultReporting.

    Values match the schema ``faultEntry.entryType`` enum exactly.
    The ``*_ALTS`` variants are LexX canonical extensions for xTract2
    disambiguation of alternative fault interpretations.
    """

    ISOLATED_FAULT = "isolatedFault"
    ISOLATED_FAULT_ALTS = "isolatedFaultAlts"
    DETECTED_FAULT = "detectedFault"
    DETECTED_FAULT_ALTS = "detectedFaultAlts"
    OBSERVED_FAULT = "observedFault"
    OBSERVED_FAULT_ALTS = "observedFaultAlts"
    CORRELATED_FAULT = "correlatedFault"
    CORRELATED_FAULT_ALTS = "correlatedFaultAlts"


@unique
class NoteLikeKind(str, Enum):
    """Kind discriminator for warnings, cautions, notes, and remarks."""

    WARNING = "warning"
    CAUTION = "caution"
    NOTE = "note"
    REMARK = "remark"


@unique
class ClassificationMethod(str, Enum):
    """Method used to classify source content as S1000D fault material."""

    RULES = "rules"
    LLM = "llm"
    ML = "ml"
    LLM_RULES = "llm+rules"
    ML_RULES = "ml+rules"
    MANUAL = "manual"


@unique
class ItemLocationCode(str, Enum):
    """S1000D item-location codes (dmCode segment)."""

    A = "A"
    B = "B"
    C = "C"
    D = "D"
    T = "T"


@unique
class AuditEventType(str, Enum):
    """Type of audit event recorded during the review workflow.

    Values are descriptive strings suitable for querying and reporting.
    """

    REVIEW_REJECTED = "review_rejected"
    REVIEW_APPROVED = "review_approved"
    RECONCILIATION_CLEANED = "reconciliation_cleaned"
    RECONCILIATION_SKIPPED = "reconciliation_skipped"


@unique
class ReconciliationOutcome(str, Enum):
    """Outcome for a single record during a reconciliation sweep.

    CLEANED — orphaned review entry was deleted successfully.
    SKIPPED — record was flagged but not safe to delete (conflict, etc.).
    ERROR   — delete was attempted but failed at the repository level.
    """

    CLEANED = "cleaned"
    SKIPPED = "skipped"
    ERROR = "error"


@unique
class TableType(str, Enum):
    """Classified role of a source table within fault-module context.

    Used by the table-classifier service to label tables extracted
    from the pipeline so downstream mappers know how to consume them.
    """

    LRU_LIST = "lru_list"
    SRU_LIST = "sru_list"
    SPARES = "spares"
    SUPPORT_EQUIPMENT = "support_equipment"
    SUPPLIES = "supplies"
    FAULT_CODE_TABLE = "fault_code_table"
    GENERAL = "general"
    UNKNOWN = "unknown"
